# Generated by Django 2.2.6 on 2019-10-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
