# Generated by Django 2.2.6 on 2019-11-01 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_info',
            fields=[
                ('Bid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=100)),
                ('beat_name', models.CharField(max_length=100)),
                ('beat', models.FileField(upload_to='beats')),
                ('genre', models.CharField(max_length=30)),
                ('beat_img', models.ImageField(upload_to='beat_img')),
                ('beat_desc', models.TextField(max_length=2000)),
                ('beat_date', models.DateTimeField(auto_now_add=True)),
                ('listens', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
