# Generated by Django 2.2.6 on 2019-11-03 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0003_work_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_info',
            name='Bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(max_length=2000)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.work_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.work_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
