# Generated by Django 2.2.6 on 2019-11-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0007_auto_20191103_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhistory',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.work_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='history',
        ),
    ]
