# Generated by Django 2.2.6 on 2019-12-20 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0008_auto_20191104_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_info',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.work_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
