# Generated by Django 2.2.6 on 2020-01-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0011_auto_20191225_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='bought',
            fields=[
                ('bbid', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('b_img', models.ImageField(upload_to='bb_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
