# Generated by Django 2.2.6 on 2019-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_quote_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('help_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
