# Generated by Django 2.2.6 on 2019-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191215_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='back_photo',
            field=models.ImageField(default='ap_default.jpg', upload_to='verifi_back'),
        ),
        migrations.AddField(
            model_name='verification',
            name='front_photo',
            field=models.ImageField(default='ap_default.jpg', upload_to='verifi_front'),
        ),
    ]
