# Generated by Django 2.2.6 on 2019-12-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191218_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='veri_submit',
            field=models.BooleanField(default=False),
        ),
    ]
