# Generated by Django 2.2.6 on 2019-12-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_profile_veri_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='advice',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('Y', 'Youtube'), ('I', 'Instagram'), ('F', 'Facebook'), ('S', 'Snapchat')], default='Y', max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
