# Generated by Django 2.2.6 on 2019-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_cart_itemcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_info',
            name='genre',
            field=models.CharField(choices=[('R', 'Rock'), ('E', 'Electric'), ('Hh', 'Hip Hop'), ('C', 'Country'), ('t', 'Techno/trance'), ('Db', 'Drum And Bass')], default='R', max_length=30),
        ),
    ]
