# Generated by Django 2.2.6 on 2019-11-03 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='verification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('vtype', models.CharField(max_length=200)),
                ('vno', models.CharField(max_length=100)),
            ],
        ),
    ]
