# Generated by Django 2.2.6 on 2019-12-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_help'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='helpinfo',
        ),
    ]
