# Generated by Django 2.2.6 on 2019-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191217_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='email',
            field=models.EmailField(default='silever@chords.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='phone',
            field=models.CharField(default='000000000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vno',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vtype',
            field=models.CharField(default='vtype', max_length=200),
        ),
    ]
