# Generated by Django 2.2.6 on 2020-01-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='platform',
            field=models.CharField(choices=[('Y', 'Youtube'), ('I', 'Instagram'), ('F', 'Facebook'), ('S', 'Snapchat'), ('U', 'Us')], default='Y', max_length=20),
        ),
    ]
